### ISSUE TITLE
Image size issue?

### ISSUE THREAD

**Issue by jhchnc** [lunapaint/vscode-luna-paint#84] opened 2021-07-22 21:03 UTC
An image shows in the layers tool and minimap, but not the editor itself.  The image box is just black.  

However, if I crop to a _small_enough_ size, then the image will render.  If I crop to a size "too big", it will not.  I am not sure what the thresholds are, however it seems like maybe image memory consumption is an issue?  Or perhaps a setting I'm not aware of, but control is VS Code?

Many thanks.  If I trim the image to a workable size, it's a very handle tool!

I use an Ubuntu laptop, 18.04.

**Comment by Tyriar** [comment] 2021-07-22 21:54
What size image are we talking about? Very large images work on my machine and I typically test to make sure 10000x10000 work. Could you also open devtools (Help > Toggle Developer Tools) and check if there are any errors?

**Comment by Tyriar** [comment] 2021-11-27 17:50
Closing off as I can't reproduce

**Closed by Tyriar** 2021-11-27 17:50 UTC
Labels: needs more info
