### ISSUE TITLE
customizable sensitivity for scrolling/panning/zooming

### ISSUE THREAD

**Issue by runaroundontheground** [lunapaint/vscode-luna-paint#184] opened 2023-05-15 20:02 UTC
when zooming, panning, or scrolling on a trackpad (with a Chromebook at least) the sensitivity is very high

**Comment by Tyriar** [comment] 2023-05-16 16:55
duplicate of https://github.com/lunapaint/vscode-luna-paint/issues/164

**Closed by Tyriar** 2023-05-16 16:55 UTC
