### ISSUE TITLE
Saving the image truncates the history!

### ISSUE THREAD

**Issue by MonkeyNinja** [lunapaint/vscode-luna-paint#110] opened 2021-11-26 10:41 UTC
Issue Type: <b>Bug</b>

As Title... :-(

**Comment by Tyriar** [comment] 2021-11-27 17:48
I can't reproduce this, probably some edge case I'm not covering correctly. Can you record a gif of this happening with https://gifcap.dev/ ?

**Comment by Tyriar** [comment] 2021-11-27 18:02
Also, you might be seeing https://github.com/lunapaint/vscode-luna-paint/issues/24?

**Comment by Tyriar** [comment] 2022-02-22 11:52
Need some more information to be able to action this so closing off

**Closed by Tyriar** 2022-02-22 11:52 UTC
Labels: needs more info
